from typing import Literal

FILE_TYPES = Literal[
    "Test Script",
    "Page Object",
    "API Client",
    "Test Data",
    "Configuration",
    "Utility",
    "Test Helper",
    "Test Suite",
    "Mock/Stub",
    "Logging/Reporting",
    "CI/CD Config",
    "Documentation",
    "Framework Core",
    "Mobile Page/Screen Object",
    "Test Runner",
    "Locator Repository",
    "Performance Test Script",
    "Security Test Script",
    "Test Hook",
    "Environment Setup",
    "Assertion Library",
    "Test Framework Extension",
    "Test Middleware",
    "Test Data Management",
    "Test Orchestration",
    "Test Analytics",
    "Cross-browser Testing",
    "Accessibility Testing",
    "Visual Testing",
    "Test Contract",
    "Test Database",
    "Test Network Configuration",
    "Test Monitoring",
    "Other",
]
